export const MOCK_EMPLOYEES = [
  {
    id: "emp-hyd-01",
    name: "Aarav Sharma",
    email: "aarav.sharma@company.com",
    department: "Engineering",
    officeLocation: "HYD",
    status: "ACTIVE",
    startDate: "2022-03-15",
    notes: "Lead Fullstack Engineer, Tech Lead Pod Alpha",
  },
  {
    id: "emp-hyd-02",
    name: "Priya Patel",
    email: "priya.patel@company.com",
    department: "Product",
    officeLocation: "HYD",
    status: "ACTIVE",
    startDate: "2023-01-10",
    notes: "Staff Product Manager for Enterprise Core",
  },
  {
    id: "emp-hyd-03",
    name: "Rohan Verma",
    email: "rohan.verma@company.com",
    department: "DevOps & Cloud",
    officeLocation: "HYD",
    status: "ACTIVE",
    startDate: "2022-07-01",
    notes: "Principal Cloud Platform Architect",
  },
  {
    id: "emp-hyd-04",
    name: "Ananya Rao",
    email: "ananya.rao@company.com",
    department: "Quality Assurance",
    officeLocation: "HYD",
    status: "ACTIVE",
    startDate: "2023-05-18",
    notes: "SDET Lead",
  },
  {
    id: "emp-hyd-05",
    name: "Divya Krishnan",
    email: "divya.krishnan@company.com",
    department: "Human Resources",
    officeLocation: "HYD",
    status: "ACTIVE",
    startDate: "2021-11-01",
    notes: "People Operations Manager",
  },
  {
    id: "emp-mum-01",
    name: "Neha Joshi",
    email: "neha.joshi@company.com",
    department: "Marketing",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2023-02-15",
    notes: "Senior Growth Marketing Lead",
  },
  {
    id: "emp-mum-02",
    name: "Siddharth Nair",
    email: "siddharth.nair@company.com",
    department: "Finance & Accounts",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2021-08-20",
    notes: "Financial Controller",
  },
  {
    id: "emp-mum-03",
    name: "Kavita Singhania",
    email: "kavita.singhania@company.com",
    department: "UI/UX Design",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2022-10-05",
    notes: "Lead Product Designer",
  },
  {
    id: "emp-mum-04",
    name: "Aditya Kapoor",
    email: "aditya.kapoor@company.com",
    department: "Sales & Partnerships",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2023-06-01",
    notes: "Enterprise Account Executive",
  },
  {
    id: "emp-off-01",
    name: "Arjun Mehta",
    email: "arjun.mehta@company.com",
    department: "Engineering",
    officeLocation: "MUM",
    status: "OFFBOARDED",
    startDate: "2021-04-10",
    endDate: "2024-01-31",
    notes: "Former Senior Backend Developer",
  },
];

export const MOCK_ASSETS = [
  {
    id: "ast-001",
    assetTag: "AST-LAP-001",
    name: 'MacBook Pro 16" M2 Max',
    category: "Laptop",
    brand: "Apple",
    model: "MacBook Pro 16 (2023)",
    serialNumber: "C02G1234MD6R",
    status: "IN_USE",
    officeLocation: "HYD",
    purchaseDate: "2023-04-15",
    vendor: "Apple India Direct",
    warrantyExpiry: "2026-04-15",
    accessories: "140W USB-C Power Adapter, MagSafe 3 Cable, USB-C Hub",
    notes: "Assigned to Lead Engineer. M2 Max 32GB RAM / 1TB SSD.",
    employeeId: "emp-hyd-01",
    employee: MOCK_EMPLOYEES[0],
    assignmentHistory: [
      {
        id: "ah-01",
        assignedDate: "2023-04-16",
        returnedDate: null,
        notes: "Initial issuance upon joining Pod Alpha",
        employee: MOCK_EMPLOYEES[0],
      },
    ],
    maintenanceLogs: [],
    disposalRecord: null,
  },
  {
    id: "ast-002",
    assetTag: "AST-LAP-002",
    name: 'MacBook Pro 14" M1 Pro',
    category: "Laptop",
    brand: "Apple",
    model: "MacBook Pro 14 (2021)",
    serialNumber: "C02F9876MD6Q",
    status: "IN_USE",
    officeLocation: "HYD",
    purchaseDate: "2022-01-20",
    vendor: "Unicorn Reseller",
    warrantyExpiry: "2025-01-20",
    accessories: "67W USB-C Power Adapter, USB-C Cable",
    notes: "Standard developer configuration. 16GB RAM / 512GB SSD.",
    employeeId: "emp-hyd-04",
    employee: MOCK_EMPLOYEES[3],
    assignmentHistory: [
      {
        id: "ah-02",
        assignedDate: "2023-05-19",
        returnedDate: null,
        notes: "Assigned to SDET Lead",
        employee: MOCK_EMPLOYEES[3],
      },
    ],
    maintenanceLogs: [],
    disposalRecord: null,
  },
  {
    id: "ast-003",
    assetTag: "AST-LAP-003",
    name: "Dell XPS 15 9530",
    category: "Laptop",
    brand: "Dell",
    model: "XPS 15 9530 (i9/32GB/1TB)",
    serialNumber: "DLXPS9530-8842",
    status: "IN_USE",
    officeLocation: "HYD",
    purchaseDate: "2023-08-10",
    vendor: "Dell India Official",
    warrantyExpiry: "2026-08-10",
    accessories: "130W Type-C Adapter, Dell Premier Sleeve",
    notes: "High performance workstation for DevOps architecture",
    employeeId: "emp-hyd-03",
    employee: MOCK_EMPLOYEES[2],
    assignmentHistory: [
      {
        id: "ah-03",
        assignedDate: "2023-08-12",
        returnedDate: null,
        notes: "Primary Cloud Architect Laptop",
        employee: MOCK_EMPLOYEES[2],
      },
    ],
    maintenanceLogs: [],
    disposalRecord: null,
  },
  {
    id: "ast-004",
    assetTag: "AST-LAP-004",
    name: "ThinkPad X1 Carbon Gen 11",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon Gen 11",
    serialNumber: "LNV-X1C11-0092",
    status: "IN_USE",
    officeLocation: "HYD",
    purchaseDate: "2023-06-01",
    vendor: "Lenovo Commercial India",
    warrantyExpiry: "2026-06-01",
    accessories: "65W USB-C GaN Charger, ThinkPad Sleeve",
    notes: "Ultra-portable laptop for Product Management",
    employeeId: "emp-hyd-02",
    employee: MOCK_EMPLOYEES[1],
    assignmentHistory: [
      {
        id: "ah-04",
        assignedDate: "2023-06-02",
        returnedDate: null,
        notes: "Assigned to Product Manager",
        employee: MOCK_EMPLOYEES[1],
      },
    ],
    maintenanceLogs: [],
    disposalRecord: null,
  },
  {
    id: "ast-005",
    assetTag: "AST-MON-001",
    name: 'Dell UltraSharp 27" 4K (U2723QE)',
    category: "Monitor",
    brand: "Dell",
    model: "U2723QE 4K USB-C Hub Monitor",
    serialNumber: "CN-0U2723QE-72841",
    status: "IN_USE",
    officeLocation: "HYD",
    purchaseDate: "2023-03-20",
    vendor: "CompuSystems HYD",
    warrantyExpiry: "2026-03-20",
    accessories: "USB-C to USB-C Cable, DisplayPort Cable, Power Cord",
    notes: "Dual monitor desk setup HYD-D-102",
    employeeId: "emp-hyd-01",
    employee: MOCK_EMPLOYEES[0],
    assignmentHistory: [
      {
        id: "ah-05",
        assignedDate: "2023-03-21",
        returnedDate: null,
        notes: "Desk monitor allocation",
        employee: MOCK_EMPLOYEES[0],
      },
    ],
    maintenanceLogs: [],
    disposalRecord: null,
  },
  {
    id: "ast-006",
    assetTag: "AST-MON-002",
    name: 'LG UltraFine 32" 4K Ergonomic',
    category: "Monitor",
    brand: "LG",
    model: "32UN880-B Ergo",
    serialNumber: "LG32UN880-99120",
    status: "IN_USE",
    officeLocation: "MUM",
    purchaseDate: "2022-11-15",
    vendor: "LG Electronics India",
    warrantyExpiry: "2025-11-15",
    accessories: "USB-C Cable, Ergo Desk Arm Clamp",
    notes: "High color accuracy 4K display for UI/UX Design",
    employeeId: "emp-mum-03",
    employee: MOCK_EMPLOYEES[7],
    assignmentHistory: [
      {
        id: "ah-06",
        assignedDate: "2022-11-16",
        returnedDate: null,
        notes: "Design workstation monitor",
        employee: MOCK_EMPLOYEES[7],
      },
    ],
    maintenanceLogs: [],
    disposalRecord: null,
  },
  {
    id: "ast-007",
    assetTag: "AST-LAP-005",
    name: "MacBook Air 15\" M2",
    category: "Laptop",
    brand: "Apple",
    model: "MacBook Air 15 (2023)",
    serialNumber: "C02MBA15M2-441",
    status: "IN_STOCK",
    officeLocation: "HYD",
    purchaseDate: "2023-09-01",
    vendor: "Apple India Direct",
    warrantyExpiry: "2026-09-01",
    accessories: "35W Dual Port Compact Adapter, MagSafe 3 Cable",
    notes: "Ready in HYD Locker B-04 for new onboarding",
    employeeId: null,
    employee: null,
    assignmentHistory: [],
    maintenanceLogs: [],
    disposalRecord: null,
  },
  {
    id: "ast-008",
    assetTag: "AST-LAP-006",
    name: "Dell Latitude 5440",
    category: "Laptop",
    brand: "Dell",
    model: "Latitude 5440 (i5/16GB/512GB)",
    serialNumber: "DLLAT5440-1102",
    status: "IN_STOCK",
    officeLocation: "MUM",
    purchaseDate: "2023-10-15",
    vendor: "Dell India Official",
    warrantyExpiry: "2026-10-15",
    accessories: "65W Type-C Power Adapter",
    notes: "Ready in MUM Locker A-12",
    employeeId: null,
    employee: null,
    assignmentHistory: [],
    maintenanceLogs: [],
    disposalRecord: null,
  },
];
