export const MOCK_EMPLOYEES = [
  {
    id: "emp-01",
    name: "Anirudha Choudhari",
    email: "anirudha.choudhari@company.com",
    department: "Engineering",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2018-12-01",
    notes: "Senior Lead",
  },
  {
    id: "emp-02",
    name: "Kaustubh Mhatre",
    email: "kaustubh.mhatre@company.com",
    department: "Engineering",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2019-10-01",
    notes: "Technical Director",
  },
  {
    id: "emp-03",
    name: "Yash Khandagle",
    email: "yash.khandagle@company.com",
    department: "Engineering",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2022-06-24",
    notes: "Fullstack Engineer",
  },
  {
    id: "emp-04",
    name: "Muskan Hingorani",
    email: "muskan.hingorani@company.com",
    department: "Engineering",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2020-11-29",
    notes: "Software Engineer",
  },
  {
    id: "emp-05",
    name: "Krishi Doshi",
    email: "krishi.doshi@company.com",
    department: "Sales",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2020-11-29",
    notes: "Sales Specialist",
  },
  {
    id: "emp-06",
    name: "Tejaswi Mane",
    email: "tejaswi.mane@company.com",
    department: "Human Resources",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2021-06-23",
    notes: "Talent Acquisition Lead",
  },
  {
    id: "emp-07",
    name: "Shivam Singh",
    email: "shivam.singh@company.com",
    department: "Engineering",
    officeLocation: "MUM",
    status: "ACTIVE",
    startDate: "2023-03-25",
    notes: "Software Engineer",
  },
  {
    id: "emp-08",
    name: "Pavan Kumar Kathi",
    email: "pavan.kumar.kathi@company.com",
    department: "Engineering",
    officeLocation: "HYD",
    status: "ACTIVE",
    startDate: "2023-03-25",
    notes: "Hyderabad IT Team",
  },
];

export const MOCK_ASSETS = [
  {
    id: "ast-wb-74",
    assetTag: "WB-74",
    name: "Lenovo Laptop i7 8th Gen",
    category: "Laptop",
    brand: "Lenovo",
    model: "i7 8th Gen 16GB 1TB SSD",
    serialNumber: "PF16MZ17",
    status: "IN_USE",
    officeLocation: "MUM",
    purchaseDate: "2018-12-01",
    vendor: "Lenovo Direct",
    warrantyExpiry: "2021-12-01",
    accessories: "Yes",
    notes: "Laptop is in good condition",
    sesaId: null,
    processor: "i7 8th Gen",
    ram: "16 GB",
    storage: "1 TB SSD",
    configuration: 'i7;8th Gen;16GB RAM;64 Bit OS;1TB SSD;:14"FHD Display',
    inspectionDone: "NO",
    invoiceLink: null,
    warrantyStartDate: "2018-12-01",
    warrantyEndDate: "2021-12-01",
    extendWarrantyDate: "2021-12-01",
    extendUpto: null,
    serviceHistory: null,
    finalSummary: "Laptop is in good condition",
    auditDate: null,
    antivirus: "NO",
    charger: "Yes",
    currentUser: "Anirudha Choudhari",
    lastUser: "NA",
    stateDetail: "In Use",
    employeeId: "emp-01",
    employee: MOCK_EMPLOYEES[0],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    assignments: [],
    maintenance: [],
    disposals: [],
  },
  {
    id: "ast-wb-todo-02",
    assetTag: "WB-TODO-02",
    name: "Apple MacBook Core i5",
    category: "Laptop",
    brand: "Apple",
    model: "Core i5 8GB 2133MHz",
    serialNumber: "C02YQ4GALVDG",
    status: "IN_USE",
    officeLocation: "MUM",
    purchaseDate: "2019-10-01",
    vendor: "Apple Authorized",
    warrantyExpiry: "2022-10-01",
    accessories: "Yes",
    notes: "Out Of Warrenty",
    sesaId: null,
    processor: "2.4 GHz Intel Core i5",
    ram: "8 GB",
    storage: "256 GB SSD",
    configuration: "2.4 GHz Intel Core i5, 8 GB 2133 MHz LPDDR3, Intel Iris Plus Graphics 655 1536 MB",
    inspectionDone: "NO",
    invoiceLink: null,
    warrantyStartDate: null,
    warrantyEndDate: null,
    extendWarrantyDate: null,
    extendUpto: null,
    serviceHistory: null,
    finalSummary: "Out Of Warrenty",
    auditDate: null,
    antivirus: "Yes",
    charger: "Yes",
    currentUser: "Kaustubh Mhatre",
    lastUser: "NA",
    stateDetail: "In Use",
    employeeId: "emp-02",
    employee: MOCK_EMPLOYEES[1],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    assignments: [],
    maintenance: [],
    disposals: [],
  },
  {
    id: "ast-wb-186",
    assetTag: "WB-186",
    name: "Dell Vostro 15 3510",
    category: "Laptop",
    brand: "Dell",
    model: "Vostro 15 3510",
    serialNumber: "HL5RJQ3",
    status: "IN_USE",
    officeLocation: "MUM",
    purchaseDate: "2022-06-24",
    vendor: "Dell Direct",
    warrantyExpiry: "2026-06-29",
    accessories: "Yes",
    notes: null,
    sesaId: null,
    processor: "i5 11th Gen",
    ram: "32 GB",
    storage: "1 TB SSD",
    configuration: "i5;11th gen;15:FHD display;16GB RAM;3200MHz;512GB SSD",
    inspectionDone: "Yes",
    invoiceLink: null,
    warrantyStartDate: null,
    warrantyEndDate: "2025-06-30",
    extendWarrantyDate: "2026-06-29",
    extendUpto: null,
    serviceHistory: null,
    finalSummary: null,
    auditDate: "April",
    antivirus: "NA",
    charger: "Yes",
    currentUser: "Yash Khandagle",
    lastUser: "Siddhesh Wayal\nPratiksha Salunkhe\nNIkhil Kamble\nNew Machine",
    stateDetail: "In Use",
    employeeId: "emp-03",
    employee: MOCK_EMPLOYEES[2],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    assignments: [],
    maintenance: [],
    disposals: [],
  },
  {
    id: "ast-wb-151",
    assetTag: "WB-151",
    name: "Dell Vostro 3500",
    category: "Laptop",
    brand: "Dell",
    model: "Vostro 3500",
    serialNumber: "5GY84F3",
    status: "IN_STOCK",
    officeLocation: "MUM",
    purchaseDate: "2021-06-20",
    vendor: "Invoice Link",
    warrantyExpiry: "2025-02-04",
    accessories: "2 charger with same tag Yes",
    notes: null,
    sesaId: "SESA843540",
    processor: "i5 11th Gen",
    ram: "16 GB",
    storage: "1 TB SSD",
    configuration: "I5;16 GB RAM - 3200 MHz;512 GB SSD; No HDD",
    inspectionDone: "Yes",
    invoiceLink: "Invoice Link",
    warrantyStartDate: "2021-06-20",
    warrantyEndDate: null,
    extendWarrantyDate: "2025-02-04",
    extendUpto: null,
    serviceHistory: null,
    finalSummary: null,
    auditDate: "April",
    antivirus: "NA",
    charger: "2 charger with same tag\nYes",
    currentUser: "IN Stock",
    lastUser: "Pravin (ARC Eng)\nSameer Shah (Tester)\nTejaswi(Hiring)\nYash Sonparote\nOmkar Patil\nRohan Choudhari\nVijayalakshmi Nadar\nChinmay Parab\nNew Machine",
    stateDetail: "Usable-SESA",
    employeeId: null,
    employee: null,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    assignments: [],
    maintenance: [],
    disposals: [],
  },
  {
    id: "ast-wb-261",
    assetTag: "WB-261",
    name: "Lenovo ThinkPad E16 Gen 2",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad E16 Gen 2 S03U00",
    serialNumber: "PF5E9ALA",
    status: "IN_USE",
    officeLocation: "MUM",
    purchaseDate: "2025-06-26",
    vendor: "Invoice",
    warrantyExpiry: "2030-06-01",
    accessories: "Yes",
    notes: null,
    sesaId: "SESA847296",
    processor: "Intel Ultra 7 (155U)",
    ram: "40 GB",
    storage: "1 TB SSD",
    configuration: null,
    inspectionDone: "Yes",
    invoiceLink: "Invoice",
    warrantyStartDate: "2025-06-26",
    warrantyEndDate: "2028-06-26",
    extendWarrantyDate: "2028-06-26",
    extendUpto: "1 June 30",
    serviceHistory: null,
    finalSummary: null,
    auditDate: null,
    antivirus: null,
    charger: "Yes",
    currentUser: "Mamta Sawant",
    lastUser: "In Stock (HYD Smart Techies)\nSivaji SatrasupalliSnehil Nair\nNew Machine",
    stateDetail: "In Use",
    employeeId: null,
    employee: null,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    assignments: [],
    maintenance: [],
    disposals: [],
  },
  {
    id: "ast-wbm-004",
    assetTag: "WBM-004",
    name: "Dell SE2219H",
    category: "Monitor",
    brand: "Dell",
    model: "Dell SE2219H",
    serialNumber: "87W4243",
    status: "IN_USE",
    officeLocation: "MUM",
    purchaseDate: null,
    vendor: null,
    warrantyExpiry: "2023-11-10",
    accessories: null,
    notes: "Power Board changed by Indresh It Solution Majiwada on 20th June 2026 with 7 days warranty",
    sesaId: null,
    processor: null,
    ram: null,
    storage: null,
    configuration: null,
    inspectionDone: null,
    invoiceLink: null,
    warrantyStartDate: null,
    warrantyEndDate: "2023-11-10",
    extendWarrantyDate: null,
    extendUpto: null,
    serviceHistory: "Power Board changed by Indresh It Solution Majiwada on 20th June 2026 with 7 days warranty",
    finalSummary: null,
    auditDate: null,
    antivirus: null,
    charger: null,
    currentUser: "Prolit/Amey /302",
    lastUser: "NA",
    stateDetail: "In Use",
    employeeId: null,
    employee: null,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    assignments: [],
    maintenance: [],
    disposals: [],
  },
  {
    id: "ast-wbsd-001",
    assetTag: "WBSD-001",
    name: "Logitech H111 Wired",
    category: "Support Device",
    brand: "Logitech",
    model: "H111 Wired",
    serialNumber: null,
    status: "IN_STOCK",
    officeLocation: "MUM",
    purchaseDate: "2024-11-26",
    vendor: "Amazon",
    warrantyExpiry: null,
    accessories: null,
    notes: null,
    sesaId: null,
    processor: null,
    ram: null,
    storage: null,
    configuration: null,
    inspectionDone: null,
    invoiceLink: "Amazon",
    warrantyStartDate: null,
    warrantyEndDate: null,
    extendWarrantyDate: null,
    extendUpto: null,
    serviceHistory: null,
    finalSummary: null,
    auditDate: null,
    antivirus: null,
    charger: null,
    currentUser: "In Stock (MUM)",
    lastUser: "Gorakhnath choudhary\nNew Headset",
    stateDetail: "Usable Support Device",
    employeeId: null,
    employee: null,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    assignments: [],
    maintenance: [],
    disposals: [],
  },
  {
    id: "ast-wbm-037",
    assetTag: "WBM-037",
    name: "Samsung UA55U8100F",
    category: "TV",
    brand: "Samsung",
    model: "UA55U8100F",
    serialNumber: "SN - 0B0X3PAYA08050A",
    status: "IN_USE",
    officeLocation: "MUM",
    purchaseDate: "2026-03-12",
    vendor: "Link",
    warrantyExpiry: "2030-03-16",
    accessories: null,
    notes: null,
    sesaId: null,
    processor: null,
    ram: null,
    storage: null,
    configuration: null,
    inspectionDone: null,
    invoiceLink: "Link",
    warrantyStartDate: "2026-03-16",
    warrantyEndDate: "2030-03-16",
    extendWarrantyDate: null,
    extendUpto: null,
    serviceHistory: null,
    finalSummary: null,
    auditDate: null,
    antivirus: null,
    charger: null,
    currentUser: "Vishalgad Meeting Room/ 302",
    lastUser: "NA",
    stateDetail: "In Use",
    employeeId: null,
    employee: null,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    assignments: [],
    maintenance: [],
    disposals: [],
  },
];
